### ISSUE TITLE
Runtime Package Store guidance where not available by default 

### ISSUE THREAD

**Issue by leecow** [dotnet/designs#10]
# Overview

.NET Core 2.0 includes a new package cache feature, called the Runtime Package Store, which is installed by the .NET Core 2.0 SDK. The Runtime Package Store enables creating a precompiled cache of common libraries which can be centrally provisioned and not deployed to every application reducing deployment size and startup times. Currently, the store that ships with the .NET Core 2.0 SDK contains ASP.NET Core packages. Design details can be seen in [dotnet/designs/issues/8](https://github.com/dotnet/designs/issues/8).

### Goal

The long term solution is to enable clean build-from-source behavior from the applicable components. For the 2.0 release, we need to develop clear, and clean, guidance for Red Hat customers to understand the Runtime Package Store (RPS) and easily execute steps need for applicable scenarios to install the RPS.

## Issue

The primary issue is that the ASP.NET packages that are contained in the Runtime Package Store cannot be built from source at this time and therefore cannot be distributed by Red Hat. Without the Runtime Package Store, deployment of ASP.NET Core applications will fail. A workaround is available though not recommended due to the impact on deployment size. Specify a PublishWithAspNetCoreTargetManifest flag set to false in the project file.

The issue and proposed solution described below are discussed in detail at https://github.com/aspnet/Home/issues/2033#issuecomment-306742980. Additional background available in the following issues.

* [aspnet/Coherence-Signed/issues/428](https://github.com/aspnet/Coherence-Signed/issues/428]
* (aspnet/MetaPackages/issues/149)[https://github.com/aspnet/MetaPackages/issues/149]

## Proposal

Microsoft builds RPMs for the Runtime Package Store. These packages will be published on a Microsoft product feed (https://packages.microsoft.com/) and be accessible via yum install (https://github.com/aspnet/Home/issues/2033).

The proposed solution can be tested now using the Preview 2 release though Preview 2 will need to be manually downloaded and installed as it is not available through the SCL.

### Download the rpm and install locally

Running the following script will download and install the Runtime Package Store to `/opt/rh/rh-dotnet20/root/usr/lib64/dotnet`. **Note:** The default 1.1 install location is `rh-dotnetcore11` so the RPM may need to be updated to `rh-dotnetcore20`.

``` bash
curl -sSL -o aspnetcore-store-2.0.0-preview2-final-rhel-x64.rpm https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0-preview2-25407-01/gpg-signed/aspnetcore-store-2.0.0-preview2-final-rhel-x64.rpm`
sudo yum -ivh aspnetcore-store-2.0.0-preview2-final-rhel-x64.rpm
```

### Register the Microsoft product feed and yum/dinf install

Running the following script will register the Microsoft product feed and install the Runtime Package store to `/opt/rh/rh-dotnet20/root/usr/lib64/dotnet`. **Note:** The default 1.1 install location is `rh-dotnetcore11` so the RPM may need to be updated to `rh-dotnetcore20`.

``` bash
sudo sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnet.repo'
yum check-update
yum install aspnetcore-store-2.0.0-preview2-final-rhel-x64.rpm
```

/cc @richlander @DamianEdwards @omajid @tmds

**Comment by omajid** [comment]
> Currently, the store that ships with the .NET Core 2.0 SDK contains ASP.NET Core packages

I believe it also includes EF Core packages as well as many other packages.

**Comment by leecow** [comment]
Updates based on comments: 

* PublishWithAspNetCoreTargetManifest details included as an option
* Made reference to RPS contents more generic: "... packages common to ASP.NET Core applications ..."
* Fixed package name in yum steps

**Comment by natemcmaster** [comment]
Even with the improvements to the error message that we made for 2.0.0 RTM, I'm still seeing users frequently hitting this issue. Do we have plans to further address this? 

Linked issues
 - https://github.com/aspnet/aspnet-docker/issues/286
 - https://github.com/dotnet/dotnet-docker/issues/283
 - https://github.com/dotnet/dotnet-docker/issues/279
 - https://github.com/dotnet/cli/issues/7680
 - https://github.com/dotnet/cli/issues/6516
 - https://stackoverflow.com/questions/45377365/an-assembly-specified-in-the-application-dependencies-manifest-was-not-found
 - https://stackoverflow.com/questions/45272458/self-contained-deployment-net-core-app-in-ubuntu
 - https://stackoverflow.com/questions/45720022/missing-runtime-store-error-on-linux-with-net-core-2-0-runtime-only

**Comment by Petermarcu** [comment]
I wouldn't find that error message very helpful. What it really needs to say is, "You've targeted ASP.NET and ASP.NET isn't installed. Go here to install it."

Here is the example of what it is today. How would I translate that into, I'm missing the asp.net platform that I targeted?

```
Error:
An assembly specified in the application dependencies manifest (*****.Web.deps.json) was not found:
package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml
```

**Comment by natemcmaster** [comment]
@Petermarcu so, assuming we want this improvement, who do we make responsible to fix this? The error itself is issued by corehost (cc @steveharter @ramarag), but the instructions for installing the runtime store are owned by aspnetcore (cc @JunTaoLuo @Eilon). Today, I don't think there is a way for a runtime store author to set a fwlink or message at build-time that would appear at runtime-time on a different box.

**Comment by Petermarcu** [comment]
We should work together to make sure enough information is persisted in the resulting application to give a good message. I think that will be a combination of more information being provided in the xml that is used to trim the application that then gets written to the deps file and then read.

Honestly, though I think we need to finish some higher level conversations about the future of the runtime store before we optimize this. It would be wasted investment if we start representing asp.net as something other than an optimzed collection of nuget packages.

**Comment by Petermarcu** [comment]
@steveharter as FYI

**Comment by JunTaoLuo** [comment]
Improving the error is one thing but can we also add some documentation and links for this as well, especially for acquisition?

The most common questions I see arise out of people bypassing the sdk and trying to install just the runtime. That will no longer work. However the documentation at https://www.microsoft.com/net/download/core#/runtime do not reflect this. The link for the runtime installer does not make it clear that the runtime store is required for aspnet apps and it does not tell users where to get it. We should also add links to the (temporarily missing) `dotnet-hosting-2.0.0` linux server hosting installers which include the runtime and the runtime store.

**Comment by JunTaoLuo** [comment]
Filed https://github.com/dotnet/core-setup/issues/3276 to track work to improve error message.
